# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    scan
    gym(scheme: "testPipelinee")
    crashlytics
  end
  lane :docuten_release do
      
      gym(
        scheme: "testPipelinee",
        workspace: "testPipelinee.xcworkspace",
        output_directory: "./build",
        configuration: "Release"
      )
  end
  lane :test do
    match(
        app_identifier: "org.reactjs.native.example.testPipelinee",
        type: "appstore",
        readonly: true
    )

    gym(
        workspace: @WORKSPACE_PATH,
        scheme: "Foo",
        configuration: "Production",
        export_method: "app-store"
    )
  end
end
